Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-insecure-test-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
